// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.AnonymousAccessMode":  schema_api_apis_cosisigsk8sio_v1alpha1_AnonymousAccessMode(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.AzureProtocol":        schema_api_apis_cosisigsk8sio_v1alpha1_AzureProtocol(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.Bucket":               schema_api_apis_cosisigsk8sio_v1alpha1_Bucket(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketClass":          schema_api_apis_cosisigsk8sio_v1alpha1_BucketClass(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketClassList":      schema_api_apis_cosisigsk8sio_v1alpha1_BucketClassList(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketList":           schema_api_apis_cosisigsk8sio_v1alpha1_BucketList(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequest":        schema_api_apis_cosisigsk8sio_v1alpha1_BucketRequest(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequestBinding": schema_api_apis_cosisigsk8sio_v1alpha1_BucketRequestBinding(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequestList":    schema_api_apis_cosisigsk8sio_v1alpha1_BucketRequestList(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequestSpec":    schema_api_apis_cosisigsk8sio_v1alpha1_BucketRequestSpec(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequestStatus":  schema_api_apis_cosisigsk8sio_v1alpha1_BucketRequestStatus(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketSpec":           schema_api_apis_cosisigsk8sio_v1alpha1_BucketSpec(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketStatus":         schema_api_apis_cosisigsk8sio_v1alpha1_BucketStatus(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.GCSProtocol":          schema_api_apis_cosisigsk8sio_v1alpha1_GCSProtocol(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.Protocol":             schema_api_apis_cosisigsk8sio_v1alpha1_Protocol(ref),
		"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.S3Protocol":           schema_api_apis_cosisigsk8sio_v1alpha1_S3Protocol(ref),
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_AnonymousAccessMode(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"private": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"boolean"},
							Format: "",
						},
					},
					"publicReadOnly": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"boolean"},
							Format: "",
						},
					},
					"publicReadWrite": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"boolean"},
							Format: "",
						},
					},
				},
			},
		},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_AzureProtocol(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"containerName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"storageAccount": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
			},
		},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_Bucket(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketSpec", "github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_BucketClass(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"provisioner": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"isDefaultBucketClass": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"boolean"},
							Format: "",
						},
					},
					"supportedProtocols": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.Protocol"),
									},
								},
							},
						},
					},
					"anonymousAccessModes": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.AnonymousAccessMode"),
									},
								},
							},
						},
					},
					"releasePolicy": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"parameters": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Allows: true,
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
				},
				Required: []string{"supportedProtocols"},
			},
		},
		Dependencies: []string{
			"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.AnonymousAccessMode", "github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.Protocol", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_BucketClassList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta"),
						},
					},
					"items": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketClass"),
									},
								},
							},
						},
					},
				},
				Required: []string{"items"},
			},
		},
		Dependencies: []string{
			"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketClass", "k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta"},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_BucketList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta"),
						},
					},
					"items": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.Bucket"),
									},
								},
							},
						},
					},
				},
				Required: []string{"items"},
			},
		},
		Dependencies: []string{
			"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.Bucket", "k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta"},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_BucketRequest(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequestSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequestStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequestSpec", "github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequestStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_BucketRequestBinding(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"namespace": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"name"},
			},
		},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_BucketRequestList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta"),
						},
					},
					"items": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequest"),
									},
								},
							},
						},
					},
				},
				Required: []string{"items"},
			},
		},
		Dependencies: []string{
			"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequest", "k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta"},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_BucketRequestSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"bucket": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"secretName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"provisioner": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"bucketPrefix": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"bucketClassName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"protocol": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"bucket", "protocol"},
			},
		},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_BucketRequestStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"phase": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
			},
		},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_BucketSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"provisioner": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"anonymousAccessMode": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.AnonymousAccessMode"),
						},
					},
					"bucketClassName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"permittedNamespaces": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"protocol": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.Protocol"),
						},
					},
					"parameters": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Allows: true,
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
				},
				Required: []string{"provisioner", "protocol"},
			},
		},
		Dependencies: []string{
			"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.AnonymousAccessMode", "github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.Protocol"},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_BucketStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"message": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"phase": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"boundBucketRequests": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequestBinding"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.BucketRequestBinding"},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_GCSProtocol(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"bucketName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"privateKeyName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"projectID": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"serviceAccount": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
			},
		},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_Protocol(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"protocolSignature": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"s3": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.S3Protocol"),
						},
					},
					"azure": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.AzureProtocol"),
						},
					},
					"gcs": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.GCSProtocol"),
						},
					},
				},
				Required: []string{"protocolSignature"},
			},
		},
		Dependencies: []string{
			"github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.AzureProtocol", "github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.GCSProtocol", "github.com/container-object-storage-interface/api/apis/cosi.sigs.k8s.io/v1alpha1.S3Protocol"},
	}
}

func schema_api_apis_cosisigsk8sio_v1alpha1_S3Protocol(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"endpoint": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"bucketName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"region": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"signatureVersion": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
			},
		},
	}
}
